2024-09-04 16:57:10,906 INFO    StreamThr :208488 [internal.py:wandb_internal():85] W&B internal server running at pid: 208488, started at: 2024-09-04 16:57:10.906385
2024-09-04 16:57:10,908 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status
2024-09-04 16:57:10,910 INFO    WriterThread:208488 [datastore.py:open_for_write():87] open: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/run-e8hn50dy.wandb
2024-09-04 16:57:10,910 DEBUG   SenderThread:208488 [sender.py:send():391] send: header
2024-09-04 16:57:10,929 DEBUG   SenderThread:208488 [sender.py:send():391] send: run
2024-09-04 16:57:13,442 INFO    SenderThread:208488 [dir_watcher.py:__init__():211] watching files in: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files
2024-09-04 16:57:13,442 INFO    SenderThread:208488 [sender.py:_start_run_threads():1200] run started: e8hn50dy with start time 1725440230.904892
2024-09-04 16:57:13,449 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: check_version
2024-09-04 16:57:13,450 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: check_version
2024-09-04 16:57:13,690 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: run_start
2024-09-04 16:57:13,707 DEBUG   HandlerThread:208488 [system_info.py:__init__():26] System info init
2024-09-04 16:57:13,707 DEBUG   HandlerThread:208488 [system_info.py:__init__():41] System info init done
2024-09-04 16:57:13,707 INFO    HandlerThread:208488 [system_monitor.py:start():194] Starting system monitor
2024-09-04 16:57:13,707 INFO    SystemMonitor:208488 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-04 16:57:13,708 INFO    HandlerThread:208488 [system_monitor.py:probe():214] Collecting system info
2024-09-04 16:57:13,708 INFO    SystemMonitor:208488 [interfaces.py:start():188] Started cpu monitoring
2024-09-04 16:57:13,711 INFO    SystemMonitor:208488 [interfaces.py:start():188] Started disk monitoring
2024-09-04 16:57:13,712 INFO    SystemMonitor:208488 [interfaces.py:start():188] Started gpu monitoring
2024-09-04 16:57:13,714 INFO    SystemMonitor:208488 [interfaces.py:start():188] Started memory monitoring
2024-09-04 16:57:13,715 INFO    SystemMonitor:208488 [interfaces.py:start():188] Started network monitoring
2024-09-04 16:57:13,723 DEBUG   HandlerThread:208488 [system_info.py:probe():152] Probing system
2024-09-04 16:57:13,776 DEBUG   HandlerThread:208488 [system_info.py:_probe_git():137] Probing git
2024-09-04 16:57:13,785 DEBUG   HandlerThread:208488 [system_info.py:_probe_git():145] Probing git done
2024-09-04 16:57:13,785 DEBUG   HandlerThread:208488 [system_info.py:probe():200] Probing system done
2024-09-04 16:57:13,785 DEBUG   HandlerThread:208488 [system_monitor.py:probe():223] {'os': 'Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2024-09-04T08:57:13.723411', 'startedAt': '2024-09-04T08:57:10.900592', 'docker': None, 'cuda': None, 'args': ('--cfg-path', '../eval_configs/main_results_all_tasks.yaml', '--tasks', 'scienceworld', '--wandb', '--log_path', '../results/gpt-3.5-turbo-0125', '--project_name', 'evaluate-gpt-35-turbo-0125', '--baseline_dir', '../data/baseline_results', '--planning', 'io', '--reasoning', 'io', '--memory', 'None', '--tooluse', 'None', '--model', 'gpt-3.5-turbo-0125'), 'state': 'running', 'program': 'eval_main_sci.py', 'codePathLocal': 'eval_main_sci.py', 'codePath': 'agentboard/eval_main_sci.py', 'git': {'remote': 'https://github.com/hkust-nlp/AgentBoard.git', 'commit': 'bb7255e2daf1989069a186dad9e53f70680961db'}, 'email': None, 'root': '/home/zky/AgentBoard_metasearch', 'host': 'LAPTOP-5PO7LLCG', 'username': 'zky', 'executable': '/home/zky/anaconda3/envs/AgentBoard/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3792.631999999999, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}, {'current': 3792.632, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 1006.853931427002, 'used': 39.464881896972656}}, 'gpu': 'NVIDIA GeForce RTX 4060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4060 Laptop GPU', 'memory_total': 8585740288}], 'memory': {'total': 7.359710693359375}}
2024-09-04 16:57:13,785 INFO    HandlerThread:208488 [system_monitor.py:probe():224] Finished collecting system info
2024-09-04 16:57:13,785 INFO    HandlerThread:208488 [system_monitor.py:probe():227] Publishing system info
2024-09-04 16:57:13,785 DEBUG   HandlerThread:208488 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-04 16:57:14,444 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/conda-environment.yaml
2024-09-04 16:57:22,882 DEBUG   HandlerThread:208488 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-04 16:57:22,883 INFO    HandlerThread:208488 [system_monitor.py:probe():229] Finished publishing system info
2024-09-04 16:57:22,885 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 16:57:22,885 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 16:57:22,885 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 16:57:22,886 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 16:57:22,886 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-04 16:57:23,064 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: python_packages
2024-09-04 16:57:23,065 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: python_packages
2024-09-04 16:57:23,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: stop_status
2024-09-04 16:57:23,066 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: stop_status
2024-09-04 16:57:23,109 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:23,446 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/conda-environment.yaml
2024-09-04 16:57:23,446 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-metadata.json
2024-09-04 16:57:23,446 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/requirements.txt
2024-09-04 16:57:23,677 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:23,677 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3459'}
2024-09-04 16:57:23,677 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:24,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:24,878 DEBUG   SenderThread:208488 [sender.py:send():391] send: telemetry
2024-09-04 16:57:25,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:25,095 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:25,095 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3459'}
2024-09-04 16:57:25,095 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:25,446 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:26,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:26,881 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 16:57:27,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:27,447 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:27,696 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:27,696 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3459'}
2024-09-04 16:57:27,696 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:27,696 INFO    wandb-upload_0:208488 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1014, in _prepare_proxy
    conn.connect()
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2911, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-09-04 16:57:28,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:29,066 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:30,067 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:31,067 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:31,449 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:32,067 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:32,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 16:57:32,355 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:32,355 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3459'}
2024-09-04 16:57:32,355 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:33,067 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:33,449 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:34,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:35,067 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:35,451 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:36,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:37,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:37,451 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:37,474 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 16:57:38,065 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: stop_status
2024-09-04 16:57:38,065 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: stop_status
2024-09-04 16:57:38,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:39,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:39,452 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:40,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:41,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:41,453 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:41,839 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/wandb-metadata.json?Expires=1725526654&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=KEZzjeuUaMNTAUji%2FIAcvWMzWGgoXJIqM80Lz%2BqxHz7q1lXdiCpan2ZsRozyOKULuhxdup4OR%2FwcMnctp0Uwywdt9bcEn4MBlxcINRFfOTKruFoloy%2FY0Ri%2F2FQcKzLjOYOBjeDZxeoswbAJvcAQUTaLRZVVW%2FEVOUcE86jUSRzpNGlSNdMTpJDNCRehpGBEV6g3UnEP%2BMiP2Ba6hudv%2Bx5UWmNyaL19eNiAHrVpKdogD2HT80SFSC9ZHct%2FIBZp2dksIBBGLywBR3guSKvm1VwzNZhloqKcOKxTZXtIK%2Bq052jT67QQaJjcj8Bk4kcMWzGvvzYeDCmK8hoDxyU7LQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:41,840 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3459'}
2024-09-04 16:57:41,840 ERROR   wandb-upload_0:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:41,862 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: log_artifact
2024-09-04 16:57:41,863 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: log_artifact
2024-09-04 16:57:42,068 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:42,453 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json
2024-09-04 16:57:42,454 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table
2024-09-04 16:57:42,454 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld
2024-09-04 16:57:42,454 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media
2024-09-04 16:57:43,109 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:43,454 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 16:57:43,780 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/g0y6cpa3-media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json
2024-09-04 16:57:44,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:44,453 INFO    wandb-upload_3:208488 [upload_job.py:push():88] Uploaded file /home/zky/.local/share/wandb/artifacts/staging/tmp638f8oli
2024-09-04 16:57:44,509 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:44,509 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:44,509 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:57:44,509 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:57:44,510 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:44,510 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:45,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:45,678 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:45,679 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:57:45,679 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:45,910 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 16:57:45,910 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:57:45,910 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:45,910 INFO    wandb-upload_2:208488 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1014, in _prepare_proxy
    conn.connect()
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/connectionpool.py", line 801, in urlopen
    retries = retries.increment(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2911, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2880, in upload_file
    response = self._upload_file_session.put(
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 589, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/zky/anaconda3/envs/AgentBoard/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-09-04 16:57:46,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:47,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:48,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:49,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:50,069 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:51,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:52,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:52,757 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:57:52,757 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:57:52,757 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:53,036 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:57:53,036 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:57:53,036 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:57:53,065 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: stop_status
2024-09-04 16:57:53,109 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:54,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:55,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:56,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:57,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:58,070 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:59,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:57:59,332 INFO    wandb-upload_0:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/xyi929zi-wandb-metadata.json
2024-09-04 16:58:00,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:01,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:02,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:02,288 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:02,288 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:58:02,288 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:02,382 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:02,382 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:58:02,382 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:03,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:04,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:05,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:06,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:07,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:08,071 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:09,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:10,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:11,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:12,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:13,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:13,715 DEBUG   SystemMonitor:208488 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-04 16:58:14,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:15,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:15,874 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:15,874 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:58:15,874 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:16,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:16,075 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:16,075 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:58:16,075 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:17,072 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:18,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:19,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:20,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:21,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:22,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:23,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:24,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:25,073 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:26,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:27,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:28,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:29,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:30,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:31,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:32,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:33,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:34,074 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:35,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:36,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:37,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:38,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:38,686 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:38,686 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:58:38,686 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:38,951 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:58:38,951 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:58:38,951 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:58:39,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:40,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:41,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:42,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:43,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:44,075 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:45,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:46,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:47,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:48,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:49,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:50,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:51,076 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:52,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:53,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:54,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:55,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:56,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:57,077 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:58,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:58:59,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:00,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:01,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:02,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:03,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:04,078 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:05,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:06,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:07,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:08,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:09,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:10,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:11,079 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:12,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:13,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:14,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:15,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:16,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:17,057 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:59:17,057 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 16:59:17,057 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:59:17,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:18,080 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:19,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:20,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:21,030 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2024-09-04 16:59:21,030 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 16:59:21,030 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 16:59:21,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:22,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:23,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:24,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:25,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:26,081 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:27,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:28,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:29,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:30,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:31,082 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:32,083 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:33,083 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:34,083 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:35,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:36,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:37,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:38,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:39,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:40,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:41,084 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:42,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:43,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:44,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:45,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:46,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:47,085 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:48,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:49,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:50,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:51,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:52,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:53,086 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:54,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:55,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:56,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:57,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:58,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 16:59:59,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:00,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:01,087 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:02,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:03,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:04,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:05,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:06,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:07,088 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:08,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:09,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:10,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:11,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:12,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:13,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:14,089 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:15,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:16,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:17,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:18,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:19,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:20,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:21,090 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:22,091 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:23,091 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:24,091 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:25,091 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:26,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:27,091 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:28,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:29,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:30,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:30,098 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/f916eb27148756e3d32f7999b7998aae?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nFaGzomImubDa9vsktwlZXrJi2YzuTR9eCblE8rac1sXYr9NGCU7wXDW6QddaI7Fi02EZd6masXJ1qsImr%2BrpIRiWbf8A2Zsd%2F%2BzlYRhXSPpRBd6DtmDYK7jKqt%2B1WtOC12DPiTI63%2FWuBo%2B4e1liC0Rvdv55Z4%2BgAbxrBN7pgXqYnseTYlMmdKEN6EtGLNvnzTFfpYDXUZWdCiHSmpFO8pN2wJBk6rwKu3OJmAUi0REULF7sJw6FjdH4gkQodAL1dL3Nep8yGxvfvK5v4yE2VKIvDv5tIqsqW5iepnl6YbbLkZnQjbL7StPszc8inbAju5ug6uX81pERTyvNRsVsA%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 17:00:30,098 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': '+RbrJxSHVuPTL3mZt5mKrg==', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '6406'}
2024-09-04 17:00:30,098 ERROR   wandb-upload_2:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 17:00:30,141 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/420095444/1179604274/7cce9a5ddf0e3269c049ea042336c9d5?Expires=1725526675&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=S2eLf2QalHNfDEOkSSHs5%2F4DwNVWXfRWzHcjviTpfsuCBuaX911Ire4QK7wPqJDE3dorIjmgsofWau9AtolQh7WVxtFBCqWO200amK77Y0nk1i74DXeecL37v8xKsoJs%2FYLjEKt6iQP%2FlIPh3waeqRTWa1FJwzbMxgCiWsFY5ATHBBPK4O4DJ0D3sKrvN%2Fc4yqQ4t5WNoP5mf%2B0luVbqU5VvNSJKpua1fZGrgLcnIaJnRYaPzSzkju4%2BFWd%2BO7Vzz3Gpsyz%2Bo0DTNq8%2F9HC%2FhTLkwQGGJDzhzY4TJ%2BS262F6ekNaQDNcTZXuV3dWYCx%2FPeHHFjP%2F2PbTzbyQJbKA9Q%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 17:00:30,141 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'fM6aXd8OMmnASeoEIzbJ1Q==', 'Content-Type': 'application/json', 'Content-Length': '2437'}
2024-09-04 17:00:30,142 ERROR   wandb-upload_4:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 17:00:31,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:32,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:32,414 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:33,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:34,092 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:35,093 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:35,387 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: log_artifact
2024-09-04 17:00:35,429 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:35,532 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json
2024-09-04 17:00:35,533 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld
2024-09-04 17:00:35,751 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:36,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:36,099 ERROR   wandb-upload_1:208488 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json?Expires=1725526847&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IM1By8pdBLXsOUcKy646UJvUzTXWBrHXRv1N3YYuP3G6mT5WKHvXxm1FazcaPj738n6oxQEQRlpBAMBWVAGUKcLsR%2BrnPffbeicMnTm9it6S%2BBUUyPhB8WWDkDs4id96i%2BDlLgirRqcLbqCNwpp%2BfxRFfWWFfC36%2B4fjys%2Bu7i8ipgwTw3f7gv0VkvPe082UEk15TtNLuojMlm1v01qNXPlmpG9FeW6rdmIueIraFyPmLer2PRNpsIVu%2FwOF0EoF9mqkUjQ7XaGS%2BzJxS5csxRgDR6aZrr%2ByKSNHN4k0dnBdKJMwIQQWajzhGcl1c3QC395K1TvLh%2F9sXniOzungEw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/eric142857-alibaba/evaluate-gpt-35-turbo-0125/e8hn50dy/media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json?Expires=1725526847&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IM1By8pdBLXsOUcKy646UJvUzTXWBrHXRv1N3YYuP3G6mT5WKHvXxm1FazcaPj738n6oxQEQRlpBAMBWVAGUKcLsR%2BrnPffbeicMnTm9it6S%2BBUUyPhB8WWDkDs4id96i%2BDlLgirRqcLbqCNwpp%2BfxRFfWWFfC36%2B4fjys%2Bu7i8ipgwTw3f7gv0VkvPe082UEk15TtNLuojMlm1v01qNXPlmpG9FeW6rdmIueIraFyPmLer2PRNpsIVu%2FwOF0EoF9mqkUjQ7XaGS%2BzJxS5csxRgDR6aZrr%2ByKSNHN4k0dnBdKJMwIQQWajzhGcl1c3QC395K1TvLh%2F9sXniOzungEw%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2024-09-04 17:00:36,099 ERROR   wandb-upload_1:208488 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '136'}
2024-09-04 17:00:36,099 ERROR   wandb-upload_1:208488 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-09-04 17:00:36,394 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:36,394 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:36,395 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:36,533 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json
2024-09-04 17:00:36,533 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json
2024-09-04 17:00:36,534 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json
2024-09-04 17:00:36,534 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json
2024-09-04 17:00:36,534 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media
2024-09-04 17:00:36,534 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld
2024-09-04 17:00:36,534 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly
2024-09-04 17:00:37,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:38,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:38,535 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/vtq27ln1-media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json
2024-09-04 17:00:38,623 INFO    wandb-upload_3:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/83wqk760-media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json
2024-09-04 17:00:38,663 INFO    wandb-upload_0:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/milo5c79-media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json
2024-09-04 17:00:39,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:39,535 INFO    wandb-upload_6:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/xkctlqr9-media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json
2024-09-04 17:00:39,543 INFO    wandb-upload_5:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/vdmeym1o-media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json
2024-09-04 17:00:40,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:41,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:42,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:43,094 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:44,095 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:45,095 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:46,095 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:00:46,760 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: log_artifact
2024-09-04 17:00:46,819 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:46,858 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:46,993 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: partial_history
2024-09-04 17:00:47,540 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/summary/metrics_6_d4741b5694b273a13228.table.json
2024-09-04 17:00:47,540 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html/summary/agent_abilities_8_2d41592c15657a797678.html
2024-09-04 17:00:47,540 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html
2024-09-04 17:00:47,541 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table
2024-09-04 17:00:47,541 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media
2024-09-04 17:00:47,541 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html
2024-09-04 17:00:47,541 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html/summary
2024-09-04 17:00:47,541 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/summary
2024-09-04 17:00:47,995 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:00:48,714 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/aggyjxjv-media/table/summary/metrics_6_d4741b5694b273a13228.table.json
2024-09-04 17:00:50,642 INFO    wandb-upload_5:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/anvuwgl0-media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html
2024-09-04 17:00:50,811 INFO    wandb-upload_0:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/9hmzkvts-media/html/summary/agent_abilities_8_2d41592c15657a797678.html
2024-09-04 17:00:52,997 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:00:57,998 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:03,000 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:08,001 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:13,002 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:18,004 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:23,006 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:28,007 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:33,009 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:38,010 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:43,012 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:48,013 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:53,015 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:01:58,017 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:03,018 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:08,020 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:13,022 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:18,023 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:23,025 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:28,026 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:33,028 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:38,030 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:40,506 INFO    wandb-upload_4:208488 [upload_job.py:push():88] Uploaded file /home/zky/.local/share/wandb/artifacts/staging/tmpcnqjts4w
2024-09-04 17:02:43,031 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:48,033 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:53,035 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:02:58,037 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:03:03,038 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:03:07,773 INFO    wandb-upload_2:208488 [upload_job.py:push():88] Uploaded file /home/zky/.local/share/wandb/artifacts/staging/tmpm5o1un1c
2024-09-04 17:03:08,040 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:03:09,311 INFO    SenderThread:208488 [sender.py:send_request_log_artifact():1537] logged artifact run-e8hn50dy-scienceworldpredictions - {'id': 'QXJ0aWZhY3Q6MTE3OTYwNDI3NA==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQyMDA5NTQ0NA==', 'latestArtifact': None}}
2024-09-04 17:03:09,319 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 17:03:09,732 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:09,732 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json with policy now
2024-09-04 17:03:09,733 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: stop_status
2024-09-04 17:03:10,209 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:10,209 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:10,209 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:10,209 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:10,210 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:10,210 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:10,210 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:10,212 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:10,212 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: log_artifact
2024-09-04 17:03:10,543 INFO    wandb-upload_6:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/cqjpf8vb-media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json
2024-09-04 17:03:10,624 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/config.yaml
2024-09-04 17:03:10,625 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_created():271] file/dir created: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-summary.json
2024-09-04 17:03:11,625 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 17:03:12,004 INFO    wandb-upload_1:208488 [upload_job.py:push():88] Uploaded file /home/zky/.local/share/wandb/artifacts/staging/tmpz5jloz8y
2024-09-04 17:03:13,042 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:03:13,341 INFO    SenderThread:208488 [sender.py:send_request_log_artifact():1537] logged artifact run-e8hn50dy-scienceworldmetrics - {'id': 'QXJ0aWZhY3Q6MTE3OTYxMDUyOA==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQyMDA5NzEwMw==', 'latestArtifact': None}}
2024-09-04 17:03:13,341 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:13,342 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json with policy now
2024-09-04 17:03:13,342 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:13,342 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:13,343 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:13,343 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:13,343 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json with policy now
2024-09-04 17:03:13,343 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:13,343 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:13,347 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:13,347 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:13,347 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json with policy now
2024-09-04 17:03:13,347 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:13,347 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:13,348 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:13,348 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:13,348 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json with policy now
2024-09-04 17:03:13,348 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:13,349 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:13,351 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:13,351 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:13,351 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json with policy now
2024-09-04 17:03:13,352 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:13,352 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:13,352 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:13,352 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:13,353 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: log_artifact
2024-09-04 17:03:13,627 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-summary.json
2024-09-04 17:03:14,467 INFO    wandb-upload_2:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/ruvvw7lu-media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json
2024-09-04 17:03:14,467 INFO    wandb-upload_0:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/424n9mfm-media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json
2024-09-04 17:03:14,932 INFO    wandb-upload_3:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/6cdq7o3c-media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json
2024-09-04 17:03:14,933 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/xxsnm4h9-media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json
2024-09-04 17:03:14,972 INFO    wandb-upload_6:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/fivvtg4a-media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json
2024-09-04 17:03:15,628 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 17:03:15,928 INFO    wandb-upload_4:208488 [upload_job.py:push():88] Uploaded file /home/zky/.local/share/wandb/artifacts/staging/tmpqc2oi0q8
2024-09-04 17:03:17,826 INFO    SenderThread:208488 [sender.py:send_request_log_artifact():1537] logged artifact run-e8hn50dy-summarymetrics - {'id': 'QXJ0aWZhY3Q6MTE3OTYxMDU4Mw==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQyMDA5NzExNg==', 'latestArtifact': None}}
2024-09-04 17:03:17,826 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:17,827 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 17:03:17,827 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/table/summary/metrics_6_d4741b5694b273a13228.table.json with policy now
2024-09-04 17:03:17,828 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:17,828 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:17,828 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:17,828 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:17,828 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html with policy now
2024-09-04 17:03:17,829 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:17,829 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:17,833 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:17,833 DEBUG   SenderThread:208488 [sender.py:send():391] send: files
2024-09-04 17:03:17,833 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file media/html/summary/agent_abilities_8_2d41592c15657a797678.html with policy now
2024-09-04 17:03:17,834 DEBUG   SenderThread:208488 [sender.py:send():391] send: history
2024-09-04 17:03:17,834 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: summary_record
2024-09-04 17:03:17,834 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:17,835 DEBUG   SenderThread:208488 [sender.py:send():391] send: exit
2024-09-04 17:03:17,835 INFO    SenderThread:208488 [sender.py:send_exit():598] handling exit code: 0
2024-09-04 17:03:17,835 INFO    SenderThread:208488 [sender.py:send_exit():600] handling runtime: 213
2024-09-04 17:03:17,837 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:17,837 INFO    SenderThread:208488 [sender.py:send_exit():606] send defer
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,838 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,839 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,839 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 0
2024-09-04 17:03:17,839 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,840 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 0
2024-09-04 17:03:17,840 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 1
2024-09-04 17:03:17,840 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,840 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 1
2024-09-04 17:03:17,840 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,840 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 1
2024-09-04 17:03:17,840 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 2
2024-09-04 17:03:17,840 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,840 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 2
2024-09-04 17:03:17,841 INFO    HandlerThread:208488 [system_monitor.py:finish():203] Stopping system monitor
2024-09-04 17:03:17,841 DEBUG   SystemMonitor:208488 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-04 17:03:17,841 DEBUG   SystemMonitor:208488 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-04 17:03:17,842 INFO    HandlerThread:208488 [interfaces.py:finish():200] Joined cpu monitor
2024-09-04 17:03:17,842 INFO    HandlerThread:208488 [interfaces.py:finish():200] Joined disk monitor
2024-09-04 17:03:17,851 INFO    HandlerThread:208488 [interfaces.py:finish():200] Joined gpu monitor
2024-09-04 17:03:17,851 INFO    HandlerThread:208488 [interfaces.py:finish():200] Joined memory monitor
2024-09-04 17:03:17,851 INFO    HandlerThread:208488 [interfaces.py:finish():200] Joined network monitor
2024-09-04 17:03:17,852 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,852 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 2
2024-09-04 17:03:17,852 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 3
2024-09-04 17:03:17,852 DEBUG   SenderThread:208488 [sender.py:send():391] send: stats
2024-09-04 17:03:17,852 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,853 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 3
2024-09-04 17:03:17,853 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,853 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 3
2024-09-04 17:03:17,853 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 4
2024-09-04 17:03:17,853 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,853 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 4
2024-09-04 17:03:17,854 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,854 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 4
2024-09-04 17:03:17,854 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 5
2024-09-04 17:03:17,854 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,854 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 5
2024-09-04 17:03:17,854 DEBUG   SenderThread:208488 [sender.py:send():391] send: summary
2024-09-04 17:03:17,855 INFO    SenderThread:208488 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-04 17:03:17,855 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,855 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 5
2024-09-04 17:03:17,855 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 6
2024-09-04 17:03:17,855 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,855 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 6
2024-09-04 17:03:17,855 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,855 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 6
2024-09-04 17:03:17,855 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 7
2024-09-04 17:03:17,855 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 17:03:17,856 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:17,856 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 7
2024-09-04 17:03:17,856 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:17,856 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 7
2024-09-04 17:03:18,043 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: keepalive
2024-09-04 17:03:18,043 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:18,630 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-summary.json
2024-09-04 17:03:18,660 INFO    wandb-upload_5:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/90tjsok5-media/table/summary/metrics_6_d4741b5694b273a13228.table.json
2024-09-04 17:03:19,317 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 8
2024-09-04 17:03:19,317 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:19,317 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:19,317 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 8
2024-09-04 17:03:19,318 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:19,318 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 8
2024-09-04 17:03:19,318 INFO    SenderThread:208488 [job_builder.py:build():440] Attempting to build job artifact
2024-09-04 17:03:19,323 INFO    SenderThread:208488 [job_builder.py:_get_source_type():569] is repo sourced job
2024-09-04 17:03:19,325 INFO    SenderThread:208488 [job_builder.py:build():545] adding wandb-job metadata file
2024-09-04 17:03:19,331 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 9
2024-09-04 17:03:19,332 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:19,332 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 9
2024-09-04 17:03:19,332 DEBUG   SenderThread:208488 [sender.py:send():391] send: artifact
2024-09-04 17:03:19,631 INFO    Thread-12 :208488 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 17:03:19,988 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/7p9sq910-media/html/summary/agent_abilities_8_2d41592c15657a797678.html
2024-09-04 17:03:20,045 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:20,235 INFO    wandb-upload_0:208488 [upload_job.py:push():130] Uploaded file /tmp/tmp25v9mfb9wandb/zh1y6yzl-media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html
2024-09-04 17:03:20,625 INFO    SenderThread:208488 [sender.py:send_artifact():1549] sent artifact job-https___github.com_hkust-nlp_AgentBoard.git_agentboard_eval_main_sci.py - {'id': 'QXJ0aWZhY3Q6MTE3MzkzNzQ2OQ==', 'state': 'COMMITTED', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQxODAyNjQ5NA==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6MTE3OTE4NjQ2Ng==', 'versionIndex': 7}}}
2024-09-04 17:03:20,625 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:20,625 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 9
2024-09-04 17:03:20,625 INFO    SenderThread:208488 [dir_watcher.py:finish():358] shutting down directory watcher
2024-09-04 17:03:20,632 INFO    SenderThread:208488 [dir_watcher.py:finish():388] scan: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files
2024-09-04 17:03:20,632 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-summary.json wandb-summary.json
2024-09-04 17:03:20,632 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-metadata.json wandb-metadata.json
2024-09-04 17:03:20,633 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log output.log
2024-09-04 17:03:20,633 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/requirements.txt requirements.txt
2024-09-04 17:03:20,633 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/config.yaml config.yaml
2024-09-04 17:03:20,635 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/conda-environment.yaml conda-environment.yaml
2024-09-04 17:03:20,644 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json media/plotly/scienceworld/progress_score_w.r.t_difficulty_5_61751bf3cd1f5ccea4a8.plotly.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json media/plotly/scienceworld/success_rate_w.r.t_difficulty_4_0c732c50695d91d056aa.plotly.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json media/plotly/scienceworld/task_reward_w.r.t_steps_3_a332fd3a8164812f9a18.plotly.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json media/plotly/scienceworld/metrics_comparison_2_ab4e5dace31fa67a23d4.plotly.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html/summary/agent_abilities_8_2d41592c15657a797678.html media/html/summary/agent_abilities_8_2d41592c15657a797678.html
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html media/html/summary/all_results_7_cc5f8e592f6bb2abbe97.html
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/summary/metrics_6_d4741b5694b273a13228.table.json media/table/summary/metrics_6_d4741b5694b273a13228.table.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json media/table/scienceworld/predictions_0_d73c3cf7bac8e290b3a1.table.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [dir_watcher.py:finish():402] scan save: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json media/table/scienceworld/metrics_1_10e73b502aa12fbed65c.table.json
2024-09-04 17:03:20,645 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 10
2024-09-04 17:03:20,645 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:20,646 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:20,646 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 10
2024-09-04 17:03:20,646 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:20,646 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 10
2024-09-04 17:03:20,646 INFO    SenderThread:208488 [file_pusher.py:finish():169] shutting down file pusher
2024-09-04 17:03:21,046 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:21,046 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:21,806 INFO    wandb-upload_1:208488 [upload_job.py:push():130] Uploaded file /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/config.yaml
2024-09-04 17:03:21,867 INFO    wandb-upload_5:208488 [upload_job.py:push():130] Uploaded file /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/requirements.txt
2024-09-04 17:03:21,962 INFO    wandb-upload_3:208488 [upload_job.py:push():130] Uploaded file /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/output.log
2024-09-04 17:03:21,973 INFO    wandb-upload_4:208488 [upload_job.py:push():130] Uploaded file /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/wandb-summary.json
2024-09-04 17:03:21,987 INFO    wandb-upload_2:208488 [upload_job.py:push():130] Uploaded file /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/files/conda-environment.yaml
2024-09-04 17:03:22,046 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:22,047 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:22,188 INFO    Thread-11 :208488 [sender.py:transition_state():626] send defer: 11
2024-09-04 17:03:22,188 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:22,188 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 11
2024-09-04 17:03:22,189 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:22,189 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 11
2024-09-04 17:03:22,189 INFO    SenderThread:208488 [file_pusher.py:join():175] waiting for file pusher
2024-09-04 17:03:22,195 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 12
2024-09-04 17:03:22,195 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:22,195 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 12
2024-09-04 17:03:22,195 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:22,195 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 12
2024-09-04 17:03:22,195 INFO    SenderThread:208488 [file_stream.py:finish():601] file stream finish called
2024-09-04 17:03:23,048 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:24,313 INFO    SenderThread:208488 [file_stream.py:finish():605] file stream finish is done
2024-09-04 17:03:24,313 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 13
2024-09-04 17:03:24,313 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:24,313 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:24,314 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 13
2024-09-04 17:03:24,314 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: status_report
2024-09-04 17:03:24,314 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:24,314 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 13
2024-09-04 17:03:24,314 INFO    SenderThread:208488 [sender.py:transition_state():626] send defer: 14
2024-09-04 17:03:24,314 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: defer
2024-09-04 17:03:24,314 INFO    HandlerThread:208488 [handler.py:handle_request_defer():184] handle defer: 14
2024-09-04 17:03:24,315 DEBUG   SenderThread:208488 [sender.py:send():391] send: final
2024-09-04 17:03:24,315 DEBUG   SenderThread:208488 [sender.py:send():391] send: footer
2024-09-04 17:03:24,315 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: defer
2024-09-04 17:03:24,315 INFO    SenderThread:208488 [sender.py:send_request_defer():622] handle sender defer: 14
2024-09-04 17:03:24,315 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:24,316 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:24,316 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: server_info
2024-09-04 17:03:24,316 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-04 17:03:24,317 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: server_info
2024-09-04 17:03:24,319 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: get_summary
2024-09-04 17:03:24,320 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: sampled_history
2024-09-04 17:03:24,320 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-04 17:03:24,948 DEBUG   SenderThread:208488 [sender.py:send_request():418] send_request: poll_exit
2024-09-04 17:03:24,948 INFO    MainThread:208488 [wandb_run.py:_footer_history_summary_info():4035] rendering history
2024-09-04 17:03:24,949 INFO    MainThread:208488 [wandb_run.py:_footer_history_summary_info():4067] rendering summary
2024-09-04 17:03:24,949 INFO    MainThread:208488 [wandb_run.py:_footer_sync_info():3994] logging synced files
2024-09-04 17:03:24,949 DEBUG   HandlerThread:208488 [handler.py:handle_request():158] handle_request: shutdown
2024-09-04 17:03:24,949 INFO    HandlerThread:208488 [handler.py:finish():882] shutting down handler
2024-09-04 17:03:25,317 INFO    WriterThread:208488 [datastore.py:close():296] close: /home/zky/AgentBoard_metasearch/agentboard/wandb/run-20240904_165710-e8hn50dy/run-e8hn50dy.wandb
2024-09-04 17:03:25,949 INFO    SenderThread:208488 [sender.py:finish():1631] shutting down sender
2024-09-04 17:03:25,949 INFO    SenderThread:208488 [file_pusher.py:finish():169] shutting down file pusher
2024-09-04 17:03:25,949 INFO    SenderThread:208488 [file_pusher.py:join():175] waiting for file pusher
